### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by twittwer** [twittwer/neo4j-paper#2]
Alle (bis Sonntag 20:00):
- [x] Sources formatiert einfügen ([APA6](https://library.sydney.edu.au/subjects/downloads/citation/APA%20Complete_2012.pdf))
- [x] Dokumente aufräumen

Alle (bis Montag 14:00):
- [x] Präsentation vollenden

***

Tobi:
- [x] Data-Structure Folie
- [x] Dokument zusammenfügen (ab Sonntag 20:00)

Manu:
- [x] Conclusion Text überarbeiten
- [x] Präsentation toll machen (ab Montag 18:00)

Kai:
- [x] Conclusion ausformulieren
- [x] Conclusion Folie

Lennart:
- [X] Query Lang Folie (Weggelassen, da nur doppelt mit Demo)
- [x] Demo vorbereiten

**Comment by twittwer** [comment]
Tobi:
- [x] Sources formatiert einfügen ([APA6](https://library.sydney.edu.au/subjects/downloads/citation/APA%20Complete_2012.pdf))
- [x] Dokumente aufräumen
- [x] Dokument zusammenfügen (ab Sonntag 20:00)
- [x] Data-Structure Folie / Präsentation vollenden

**Comment by Hurba** [comment]
@twittwer die Quellen sind noch nicht perfekt formatiert.

Im Text: Ich finde 3 Quellen direkt hintereinander etwas komisch. Kann man die nicht direkt an den dazugehörigen Satz anknüpfen ?

In der Referenzliste:
Der Titel hinter dem Datum gehört _Kursiv_ geschrieben.
Außerdem müssen gleiche Autoren und gleiches Jahr mit a und b hinter dem Jahr markiert werden.
Und man muss es nach der 1. Zeile einrücken.
Bsp.:

>Fullan, M. (1996**a**). Leadership for change. In **_International_**
>>**_handbook for educational leadership and administration_**. New
York, NY: Kluwer Academic Publishers.

>Fullan, M. (1996**b**). **_The new meaning of educational change_**.
>>London, England: Cassell

Noch ein kleines ding. Bei Paragraphen soll es anscheinend so aussehen. Nicht nur den Namen, sonder auch mitgezählt der wievielte Paragraph das schon ist. :scream:
(University of Sydney, 2010, “Who owns copyright?”, para. 1)

Sonst aber schön gemacht !
Eine Frage zum letzten Bild. Müssen da Pfeilrichtungen rein ? Weil im Code sind die Relations ja gerichtet.

Over and Out :sleeping:

**Comment by twittwer** [comment]
Wenn Quellen über >1 Zeile gehen muss ab der 2. Zeile eingerückt werden.

**Comment by Hurba** [comment]
@TrAnn3l : Die Quelle ist nicht im Text referenziert.. Neo Technology, Inc. (2017a). Cypher Query Language Developer Guides & Tutorials. Retrieved April 9, 2017, from https://neo4j.com/developer/cypher/

**Comment by TrAnn3l** [comment]
Muss sie doch auch nicht immer?

**Comment by twittwer** [comment]
@TrAnn3l @Hurba Laut Manu schon

Unreferenziert sind:
- Mahler, D. (2014). Graphendatenbank: Flexible Datenabfragen mit Neo4j
- Panzarino, O. (2014). Learning Cypher
- Neo Technology, Inc. (2017a). Cypher Query Language Developer Guides & Tutorials
- Neo Technology, Inc. (2017d). Graph DB vs RDBMS

**Comment by kai-oswald** [comment]
Habe bei mir auch noch unreferenzierte Quellen gefunden (Comparison.md):
- Neo Technology, Inc. (2017d). Graph DB vs RDBMS  

Eine Quelle hatte ich vergessen anzugeben, habe diese jetzt mit "2017e" bezeichnet.
- Neo Technology, Inc. (2017e). Neo4j and MongoDB

**Comment by TrAnn3l** [comment]
Habe meine referenzen gefixt.
Mahler, D. und 2017a eingebunden, Buch entfernt, da es sowieso nicht möglich war, seiten zu zitieren.

**Comment by twittwer** [comment]
https://github.com/ChrisB9/DBI-EBook/blob/master/markdown/TODO.md
-> you.png

**Comment by TrAnn3l** [comment]
Wie kann das zu groß sein? Ist 58x58px und nur 1,76kb groß?

**Comment by twittwer** [comment]
woher soll ich das wissen - diskutiere das bitte mit chris #7
